---

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
       proxy:
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
#      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CF_API_KEY=${YOU_API_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
      - ./configs/:/configs/
      - ./logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUB_DOMAIN}.entrypoints=http"
      - "traefik.http.routers.${SUB_DOMAIN}.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
#      - "traefik.http.middlewares.${SUB_DOMAIN}-auth.basicauth.users=${YOUR_USERNAME_PASSWORD}"  # PW Secure
      - "traefik.http.middlewares.${SUB_DOMAIN}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.${SUB_DOMAIN}.middlewares=${SUB_DOMAIN}-https-redirect"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.entrypoints=https"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
#      - "traefik.http.routers.${SUB_DOMAIN}-secure.middlewares=${SUB_DOMAIN}-auth"               # PW Secure
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls=true"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls.domains[1].main=${DOMAIN_1}"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls.domains[1].sans=*.${DOMAIN_1}"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls.domains[2].main=${DOMAIN_2}"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls.domains[2].sans=*.${DOMAIN_2}"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls.domains[3].main=${DOMAIN_3}"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls.domains[3].sans=*.${DOMAIN_3}"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.service=api@internal"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.middlewares=authentik@file"       # Authentik Proxy

  traefik-certs-dumper:
    container_name: traefik_certs-dumper
    image: ldez/traefik-certs-dumper:latest
    entrypoint: sh -c '
      apk add jq
      ; while ! [ -e /data/acme.json ]
      || ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ]; do
      sleep 1
      ; done
      && traefik-certs-dumper file --version v2 --watch
      --source /data/acme.json --dest /data/certs --domain-subdir'
    #  --source /data/acme.json --dest /data/certs --crt-ext=.pem --key-ext=.pem --domain-subdir'
    volumes:
      - ./:/data
# https://github.com/ldez/traefik-certs-dumper?tab=readme-ov-file

networks:
  proxy:
    name: proxy
